[dir]
INPUT_BASE = /glade/u/home/jtcohen/MODE/final_run
OUTPUT_BASE = /glade/derecho/scratch/jtcohen/MODE_files/output_r{RADIUS}
MET_INSTALL_DIR = /glade/work/dtcrt/METplus/casper/components/MET/installations/12.0.2
LOG_METPLUS = {LOG_DIR}/metplus.log.{INIT_BEG}.{LOG_TIMESTAMP}
METPLUS_CONF = {OUTPUT_BASE}/confs/metplus_final.conf.{INIT_BEG}.{LOG_TIMESTAMP}
TMP_DIR = {OUTPUT_BASE}/tmp/{INIT_BEG}

[config]
###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###
RADIUS = 3

FCST_MODE_INPUT_DIR =
FCST_MODE_INPUT_TEMPLATE = PYTHON_XARRAY

OBS_MODE_INPUT_DIR =
OBS_MODE_INPUT_TEMPLATE = PYTHON_XARRAY

MODE_OUTPUT_DIR = {OUTPUT_BASE}
MODE_OUTPUT_TEMPLATE = i{init?fmt=%Y%m%d}

FCST_MODE_FILE_WINDOW_BEGIN = 0
FCST_MODE_FILE_WINDOW_END = 0
OBS_MODE_FILE_WINDOW_BEGIN = 0
OBS_MODE_FILE_WINDOW_END = 0


###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###

FCST_IS_PROB = false
shift_right = 160

FCST_VAR1_NAME = {INPUT_BASE}/read_mhw_xarray.py /glade/work/jtcohen/MODE_files_final/forecast_r{RADIUS}.nc:{init?fmt=%Y%m%d}:{valid?fmt=%Y%m%d}:{shift_right} FCST {fcst_level}
FCST_VAR1_LEVELS = m01, m02, m03, m04, m05, m06, m07, m08, m09, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20

FCST_MODE_CONV_RADIUS = 0
FCST_MODE_CONV_THRESH = >0.0
FCST_MODE_MERGE_THRESH = >0.0
FCST_MODE_MERGE_FLAG = NONE

OBS_VAR1_NAME = {INPUT_BASE}/read_mhw_xarray.py /glade/work/jtcohen/MODE_files_final/observation_r{RADIUS}.nc:{init?fmt=%Y%m%d}:{valid?fmt=%Y%m%d}:{shift_right} OBS {fcst_level}
OBS_VAR1_LEVELS = "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)", "(*,*)"

OBS_MODE_CONV_RADIUS = 0
OBS_MODE_CONV_THRESH = >0.0
OBS_MODE_MERGE_THRESH = >0.0
OBS_MODE_MERGE_FLAG = NONE


###
# MODE Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#mode
###

LOG_MODE_VERBOSITY = 2

MODE_CONFIG_FILE = {PARM_BASE}/met_config/MODEConfig_wrapped

MODE_REGRID_TO_GRID = NONE

MODE_MASK_MISSING_FLAG = NONE
MODE_MASK_GRID_FLAG = NONE
MODE_MASK_POLY_FLAG = NONE

MODE_MATCH_FLAG = BOTH

MODE_OUTPUT_PREFIX = {CURRENT_FCST_LEVEL}E

MODE_MERGE_CONFIG_FILE =

MODEL = SMYLE

OBTYPE = ANALYS

MODE_GRID_RES = 100.

MODE_QUILT = FALSE

MODE_MAX_CENTROID_DIST = 1000.

MODE_WEIGHT_CENTROID_DIST = 0.
MODE_WEIGHT_BOUNDARY_DIST = 1.
MODE_WEIGHT_CONVEX_HULL_DIST = 0.
MODE_WEIGHT_ANGLE_DIFF = 0.
MODE_WEIGHT_ASPECT_DIFF = 0.
MODE_WEIGHT_AREA_RATIO = 0.
MODE_WEIGHT_INT_AREA_RATIO = 0.
MODE_WEIGHT_CURVATURE_RATIO = 0.
MODE_WEIGHT_COMPLEXITY_RATIO = 0.
MODE_WEIGHT_INTEN_PERC_RATIO = 0.
MODE_WEIGHT_INTEN_PERC_VALUE = 50

MODE_INTEREST_FUNCTION_CENTROID_DIST = (
      (             0.0, 1.0 )
      ( 2000.0/grid_res, 1.0 )
      ( 6000.0/grid_res, 0.0 )
   )
MODE_INTEREST_FUNCTION_BOUNDARY_DIST = (
      (            0.0, 1.0 )
      ( 100.0/grid_res, 0.0 )
   )
MODE_INTEREST_FUNCTION_CONVEX_HULL_DIST = (
      (            0.0, 1.0 )
      ( 4500.0/grid_res, 0.0 )
   )

MODE_TOTAL_INTEREST_THRESH = 0.7

MODE_VERIFICATION_MASK_TEMPLATE =
